[custom]
;自定义远程配置
;基于 blackmatrix7/ios_rule_script 规则

;去广告：不含（可自行添加）
;自动测速：支持
;负载均衡：支持
;微软分流：支持
;苹果分流：支持
;流媒体分流：支持
;AI平台分流：支持
;游戏平台分流：支持

;设置规则标志位
ruleset=🏠 Lan,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan_No_Resolve.yaml
ruleset=🍎 Apple,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml
ruleset=📺 BiliBili,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml
ruleset=🎬 Netflix,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_No_Resolve.yaml
ruleset=🏰 Disney,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney_No_Resolve.yaml
ruleset=📹 YouTube,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube_No_Resolve.yaml
ruleset=🎵 TikTok,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok_No_Resolve.yaml
ruleset=🌍 GlobalMedia,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml
ruleset=🤖 OpenAI,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml
ruleset=🔍 Google,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google_No_Resolve.yaml
ruleset=Ⓜ️ Microsoft,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml
ruleset=💰 PayPal,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal_No_Resolve.yaml
ruleset=📲 Telegram,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
ruleset=🎮 Steam,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam_No_Resolve.yaml
ruleset=🇨🇳 China,[]GEOIP,CN,no-resolve
ruleset=🇨🇳 China,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical_No_IPv6_No_Resolve.yaml
ruleset=🐟 Final,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 Proxy`select`[]⚡ Auto`[]🔄 RoundRobin`[]DIRECT`[]REJECT`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=⚡ Auto`url-test`.*`http://connectivitycheck.gstatic.com/generate_204`300,,50
custom_proxy_group=🔄 RoundRobin`load-balance`.*`http://connectivitycheck.gstatic.com/generate_204`300,,50`round-robin
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Proxy`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=📺 BiliBili`select`[]DIRECT`[]🚀 Proxy`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`.*
custom_proxy_group=🎬 Netflix`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🏰 Disney`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=📹 YouTube`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🎵 TikTok`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🌍 GlobalMedia`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🤖 OpenAI`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺��� United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🔍 Google`select`[]🚀 Proxy`[]DIRECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 Proxy`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=💰 PayPal`select`[]DIRECT`[]🚀 Proxy`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=📲 Telegram`select`[]🚀 Proxy`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🎮 Steam`select`[]🚀 Proxy`[]DIRECT`[]REJECT`[]⚡ Auto`[]🇭🇰 Hong Kong`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇨🇳 Taiwan`.*
custom_proxy_group=🏠 Lan`select`[]DIRECT`[]REJECT
custom_proxy_group=🇨🇳 China`select`[]DIRECT`[]REJECT`[]🚀 Proxy`[]⚡ Auto
custom_proxy_group=🐟 Final`select`[]🚀 Proxy`[]⚡ Auto`[]DIRECT`[]REJECT`.*
custom_proxy_group=🇭🇰 Hong Kong`select`(🇭🇰|港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=🇸🇬 Singapore`select`(🇸🇬|新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇯🇵 Japan`select`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=🇺🇸 United States`select`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇨🇳 Taiwan`select`(🇹🇼|台|新竹|中華電信|新北|彰化|TW|Taiwan)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.你的地址/custom_base.yml
