[custom]
;自定义远程配置
;基于 blackmatrix7/ios_rule_script 规则

;去广告：不含（可自行添加）
;自动测速：支持
;负载均衡：支持
;微软分流：支持
;苹果分流：支持
;谷歌分流：支持
;流媒体分流：支持
;AI平台分流：支持
;游戏平台分流：支持

;设置规则标志位
ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,[]GEOIP,private
ruleset=🪢 直连,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct_No_Resolve.yaml
ruleset=🪢 直连,[]GEOSITE,category-game-platforms-download@cn
ruleset=🪢 直连,[]GEOSITE,microsoft@cn
ruleset=🪢 直连,[]GEOSITE,category-games-cn
ruleset=🪢 直连,[]GEOSITE,category-games-!cn@cn
ruleset=💭 TG消息,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
ruleset=🍎 Apple,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml
ruleset=🅱️ Bilibili,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml
ruleset=🎥 Netflix,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_No_Resolve.yaml
ruleset=🐹 Disney+,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney_No_Resolve.yaml
ruleset=📹 YouTube,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube_No_Resolve.yaml
ruleset=🎶 TikTok,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok_No_Resolve.yaml
ruleset=🎵 Spotify,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify_No_Resolve.yaml
ruleset=💬 Ai平台,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml
ruleset=💬 Ai平台,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude_No_Resolve.yaml
ruleset=💬 Ai平台,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini_No_Resolve.yaml
ruleset=💬 Ai平台,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot_No_Resolve.yaml
ruleset=🔍 Google,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google_No_Resolve.yaml
ruleset=Ⓜ️ Microsoft,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml
ruleset=🎮 游戏平台,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game_No_Resolve.yaml
ruleset=💰 PayPal,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal_No_Resolve.yaml
ruleset=🌍 国外媒体,clash-classic:https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml
ruleset=🪢 直连,[]GEOSITE,cn
ruleset=🐟 漏网之鱼,[]GEOSITE,geolocation-!cn
ruleset=💭 TG消息,[]GEOIP,telegram
ruleset=🪢 直连,[]GEOIP,cn
ruleset=🐟 漏网之鱼,[]MATCH
;设置规则标志位

;设置分组标志位
custom_proxy_group=🌊 Proxy`select`[]✨ 自动选择`[]⏬ 自动回退`[]🪢 直连`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=✨ 自动选择`url-test`.*`http://connectivitycheck.gstatic.com/generate_204`300,5,30
custom_proxy_group=⏬ 自动回退`fallback`.*`http://connectivitycheck.gstatic.com/generate_204`300
custom_proxy_group=💭 TG消息`select`[]🌊 Proxy`[]🇸🇬 SG ⚡`[]🇭🇰 HK ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=🍎 Apple`select`[]🪢 直连`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=🅱️ Bilibili`select`[]🪢 直连`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=🎥 Netflix`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=🐹 Disney+`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=📹 YouTube`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=🎶 TikTok`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=🎵 Spotify`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇨🇳 TW ⚡`[]🇯🇵 JP ⚡`[]🇸🇬 SG ⚡`[]🇺🇸 US ⚡`[]🪢 直连`.*
custom_proxy_group=🌍 国外媒体`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=💬 Ai平台`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=🔍 Google`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`[]🪢 直连`.*
custom_proxy_group=Ⓜ️ Microsoft`select`[]🪢 直连`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=🎮 游戏平台`select`[]🌊 Proxy`[]🪢 直连`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=💰 PayPal`select`[]🌊 Proxy`[]🪢 直连`[]✨ 自动选择`[]⏬ 自动回退`[]🇭🇰 HK ⚡`[]🇸🇬 SG ⚡`[]🇯🇵 JP ⚡`[]🇺🇸 US ⚡`[]🇨🇳 TW ⚡`.*
custom_proxy_group=🪢 直连`select`[]DIRECT`[]🌊 Proxy
custom_proxy_group=🐟 漏网之鱼`select`[]🌊 Proxy`[]✨ 自动选择`[]⏬ 自动回退`[]🪢 直连`.*
custom_proxy_group=🇭🇰 HK ⚡`url-test`(?i)(🇭🇰|港|HK|Hong|HKG|HKT)`http://connectivitycheck.gstatic.com/generate_204`300,5,30
custom_proxy_group=🇸🇬 SG ⚡`url-test`(?i)(🇸🇬|新|狮城|SG|Singapore)`http://connectivitycheck.gstatic.com/generate_204`300,5,30
custom_proxy_group=🇯🇵 JP ⚡`url-test`(?i)(🇯🇵|日|东京|大阪|品川|埼玉|JP|Japan)`http://connectivitycheck.gstatic.com/generate_204`300,5,30
custom_proxy_group=🇺🇸 US ⚡`url-test`(?i)(🇺🇸|美|US|America|United States|UnitedState|Los Angeles|Chicago|Ashburn|Seattle|Kansas)`http://connectivitycheck.gstatic.com/generate_204`300,5,30
custom_proxy_group=🇨🇳 TW ⚡`url-test`(?i)(🇨🇳|🇼🇸|🇹🇼|台|新竹|中華電信|新北|彰化|TW|Taiwan)`http://connectivitycheck.gstatic.com/generate_204`300,5,30
;设置分组标志位

  
enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://fastly.jsdelivr.net/gh/paooloin/clash-rules@master/config/config1.yml
